export const appsConfig = {
  primary: [
    {
      id: 'gmail',
      name: 'Gmail Connection',
      displayName: 'Gmail',
      icon: '/icons/gmail.svg',
      endpoint: '/api/auth/gmail',
      status: 'active',
      type: 'oauth',
      description: 'Connect your Gmail account for email automation',
      instructions: "We'll redirect you to Google to authorize Gmail access securely.",
      fields: ['name', 'email'],
      formTitle: 'Connect Gmail',
      provider: 'gmail',
    },
    {
      id: 'hubspot',
      name: 'HubSpot Connection',
      displayName: 'HubSpot',
      icon: '/icons/hubspot.svg',
      endpoint: '/api/auth/hubspot',
      status: 'active',
      type: 'api',
      description: 'Integrate with HubSpot CRM for lead management',
      instructions: 'Enter your HubSpot Private App Token to connect your account.',
      fields: ['name', 'email', 'apiKey'], // changed from apiToken
      formTitle: 'Connect HubSpot',
      provider: 'hubspot',
    },
    {
      id: 'outlook',
      name: 'Outlook Connection',
      displayName: 'Outlook',
      icon: '/icons/outlook.svg',
      endpoint: '/api/auth/outlook',
      status: 'active',
      type: 'oauth',
      description: 'Connect Microsoft Outlook for email workflows',
      instructions: 'We will redirect you to Microsoft to authorize Outlook access securely.',
      fields: ['name', 'email'],
      formTitle: 'Connect Outlook',
      provider: 'outlook',
    },
    {
      id: 'streak',
      name: 'Streak Connection',
      displayName: 'Streak',
      icon: '/icons/streak.svg',
      endpoint: '/api/auth/streak',
      status: 'active',
      type: 'api',
      description: 'Connect Streak CRM for pipeline management',
      instructions: 'Enter your Streak API Key to connect your account.',
      fields: ['name', 'email', 'token'], // changed from apiKey
      formTitle: 'Connect Streak',
      provider: 'streak',
    },
  ],
  integrations: [
    { id: 'google-drive', name: 'Google Drive', displayName: 'G-Drive', icon: '/icons/gdrive.svg', status: 'active' },
    { id: 'google-sheets', name: 'Google Sheets', displayName: 'G-Sheet', icon: '/icons/gsheets.svg', status: 'active' },
    { id: 'dropbox', name: 'Dropbox', displayName: 'Dropbox', icon: '/icons/dropbox.svg', status: 'active' },
    { id: 'trello', name: 'Trello', displayName: 'Trello', icon: '/icons/trello.svg', status: 'active' },
    { id: 'figma', name: 'Figma', displayName: 'Figma', icon: '/icons/figma.svg', status: 'active' },
    { id: 'notion', name: 'Notion', displayName: 'Notion', icon: '/icons/notion.svg', status: 'active' },
  ],
};

export const formFields = {
  name: {
    type: 'text',
    placeholder: 'Enter Full Name',
    required: true,
    validation: (value) => value.length >= 2,
  },
  email: {
    type: 'email',
    placeholder: 'Enter Your Email',
    required: true,
    validation: (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value),
  },
  apiKey: {
    type: 'text',
    placeholder: 'Enter HubSpot Private App Token',
    required: true,
    helpText: 'Get your private app token from HubSpot Settings > Integrations > Private Apps',
  },
  token: {
    type: 'text',
    placeholder: 'Enter Streak API Key',
    required: true,
    helpText: 'Get your API key from Streak Settings > API Key',
  },
};